version: '3.9'

services:
  web:
    build: .
    container_name: krist_ecommerce_backend
    command: >
      bash -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - 9000:8000
    volumes:
      - .:/krist_ecommerce_backend
    