# Generated by Django 5.0.6 on 2024-10-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processing', 'processing'), ('delivered', 'delivered'), ('shipped', 'shipped')], default='processing', max_length=25),
        ),
    ]
